### ISSUE TITLE
startLearning is not working

### ISSUE THREAD

**Issue by juleskreutzer** [Holger-Will/node-enocean#21]
Hi,

I run enocean pi on a raspberry pi 2. I make a connection to my own server using socket.io. On the server, I can call an endpoint that should set the enocean pi in learning mode.

In your documentation you refer to startLearning(). When I use this, I get the exception that ```startLearning()```is not a function. When I call just ```startLearning``` I don't have this problem. I placed an console.log() just before the startLearning call and can verify that it will get executed.

Unfortunately, no new sensors will be recognized and the learned event will never be executed.

This is the code where I call ```startLearning```

socket.on('startLearning', function(data, callback) {

    console.log("Learning new sensors..");

    enocean.startLearning;

    enocean.on('learned', function(d) {
        console.log("I'm done learning new sensors..");
        callback(null, d);
    });
});
`

the enocean.on() call is also placed outside the socket.on() call, but without any effect.
configuration:
 - timeout: 30
 - config file path: __dirname + /data/config.json
 - sensor file path: __dirname + /data/sensors.json

**Comment by Holger-Will** [comment]
well.. yes the documentation is a bit rough currently... the event is called "start-learning"... so try

     socket.emit('start-learning', function(data, callback) {

startLearning is the API when using the enocean object... sorry :-)

**Comment by juleskreutzer** [comment]
startLearning is called form our server, probably the naming could be better. 
When I adjust my code, it will return an exception:
`
/home/yookr/Desktop/node-enocean-pi/node-enocean-pi/node_modules/node-enocean/index.js:226
                socket.on( "get-last-sensor-value" , async function( id ) {
                                                     ^^^^^
SyntaxError: missing ) after argument list
`

**Comment by Holger-Will** [comment]
that's an error of the new version 2.0.0 which was released yesterday... for the new version you need the newest node version 7.7.1. (or start your server with --harmony-async-await)
or install an old version of node-enocean

**Comment by juleskreutzer** [comment]
Even when using version 1.8.0, It is still not working.

some extra info:
this is the socket object: `var io = require('socket.io-client');
var socket = io.connect(SERVER_ADDRESS, { reconnect: true});`
and this is the enocean object:
`var enocean = require('node-enocean')({
    sensorFilePath:__dirname+"/data/sensors.json",
    configFilePath:__dirname+"/data/config.json",
    timeout:30
});`

**Comment by Holger-Will** [comment]
can i see your server code please...
you need to register your socket.io on the serverside with 

    enocean.emitters.push(io)

see the node-enocean-server-template
https://github.com/Holger-Will/node-enocean-server-template/blob/master/index.js

**Comment by juleskreutzer** [comment]
We have hosted the code on bluemix, but I have cloned a part to a private github repo. You should have an invite for it

**Comment by Holger-Will** [comment]
i have updated your private repository. please let me know if the issuei s fixed now.
also see error #23

**Comment by juleskreutzer** [comment]
Hi Holger-Will, 

I saw your commit but didn't have time to test this yet. I don't know if I have time to test it in the near future.

I'll close this issue now, if I still have a problem I will re-open it. Thanks for your help!

**Comment by Holger-Will** [comment]
Thanks!
